repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [ "--py38-plus" ]
        name: Upgrade code

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.3.0
  #   hooks:
  #     - id: codespell
  #       additional_dependencies: [ tomli ]
  #       args: ["--write-changes"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ "--fix", "--preview" ]
        exclude: "^notebooks/.*|^docs/.*"
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args: [ "--preview" ]
        exclude: "^notebooks/.*|^docs/.*"

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-admon
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-mkdocs
          - mdformat-toc
          - mdformat-gfm
        args: [ "--number" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
      - id: mypy
        args: [ ]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest -v tests
        language: system
        pass_filenames: false
        always_run: true
